### ISSUE TITLE
Heroku deployment doesn't work in Chrome

### ISSUE THREAD

**Issue by jimbofreedman** [sedubois/belong#1]
```
git clone git@github.com:sedubois/belong.git
heroku create --region eu
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v91
heroku config:set NPM_CONFIG_PRODUCTION=false
git push heroku master
heroku open
```

... works fine in Firefox 49.0.2, but in Chrome 53.0.2785.143 (64-bit), gives the console error:
`Uncaught TypeError: Cannot set property 'liftedStore' of undefined`

**Comment by sedubois** [comment]
Thanks! Yes I noticed something is fishy, but right now I suspended work on this repo and I'm exploring deploying with [Now](https://zeit.co/now) here:
https://github.com/sedubois/realate

**Comment by jimbofreedman** [comment]
If you're interested, it's nothing to do with Heroku - disabling the Redux Devtools extension in Chrome resolved the issue. I quite like Redux Devtools so I'll probably put some time into digging deeper soon.

**Comment by sedubois** [comment]
Sure, thanks for letting me know.

**Comment by sedubois** [comment]
Closing this, development now happens in https://github.com/relatenow/relate! Deployed with Zeit Now.
